use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Package {
    pub id: String,
    pub name: String,
    pub description: String,
    pub dependencies: Vec<String>,
    #[serde(rename = "estimatedTime")]
    pub estimated_time: u32, // minutes
    pub category: Category,
    pub size: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum Category {
    Foundation,
    #[serde(rename = "ML Framework")]
    MLFramework,
    #[serde(rename = "LLM Runtime")]
    LLMRuntime,
    #[serde(rename = "LLM Models")]
    LLMModels,
    #[serde(rename = "Image Generation")]
    ImageGeneration,
    #[serde(rename = "Video Generation")]
    VideoGeneration,
    #[serde(rename = "Audio/Voice")]
    AudioVoice,
    #[serde(rename = "Vision Models")]
    VisionModels,
    Application,
    Tools,
}

pub fn get_packages() -> Vec<Package> {
    vec![
        // Foundation
        Package {
            id: "core".to_string(),
            name: "Core System".to_string(),
            description: "Essential tools, NVIDIA drivers, CUDA 12.4, Node.js, Docker".to_string(),
            dependencies: vec![],
            estimated_time: 15,
            category: Category::Foundation,
            size: "~4GB".to_string(),
        },
        Package {
            id: "python".to_string(),
            name: "Python & AI Libs".to_string(),
            description: "Python 3.11+, pip, venv, numpy, scipy, pandas".to_string(),
            dependencies: vec!["core".to_string()],
            estimated_time: 5,
            category: Category::Foundation,
            size: "~500MB".to_string(),
        },

        // ML Framework
        Package {
            id: "pytorch".to_string(),
            name: "PyTorch Stack".to_string(),
            description: "PyTorch, torchvision, transformers, diffusers, accelerate".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string()],
            estimated_time: 10,
            category: Category::MLFramework,
            size: "~8GB".to_string(),
        },

        // LLM Runtime
        Package {
            id: "ollama".to_string(),
            name: "Ollama LLM Server".to_string(),
            description: "Ollama service with systemd integration".to_string(),
            dependencies: vec!["core".to_string()],
            estimated_time: 3,
            category: Category::LLMRuntime,
            size: "~200MB".to_string(),
        },

        // LLM Models - Small (7-8B)
        Package {
            id: "llama-3_3-8b".to_string(),
            name: "Llama 3.3 8B".to_string(),
            description: "Meta's latest Llama model, efficient and capable".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 8,
            category: Category::LLMModels,
            size: "~5GB".to_string(),
        },
        Package {
            id: "mistral-7b".to_string(),
            name: "Mistral 7B".to_string(),
            description: "High-performance 7B model from Mistral AI".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 6,
            category: Category::LLMModels,
            size: "~4GB".to_string(),
        },
        Package {
            id: "qwen-2_5-7b".to_string(),
            name: "Qwen 2.5 7B".to_string(),
            description: "Alibaba's multilingual model with strong coding abilities".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 7,
            category: Category::LLMModels,
            size: "~4.5GB".to_string(),
        },
        Package {
            id: "phi-4".to_string(),
            name: "Phi-4".to_string(),
            description: "Microsoft's small but powerful model".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 5,
            category: Category::LLMModels,
            size: "~3.8GB".to_string(),
        },

        // LLM Models - Medium (14-34B)
        Package {
            id: "qwen-2_5-14b".to_string(),
            name: "Qwen 2.5 14B".to_string(),
            description: "Balanced performance and efficiency".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 12,
            category: Category::LLMModels,
            size: "~9GB".to_string(),
        },
        Package {
            id: "mixtral-8x7b".to_string(),
            name: "Mixtral 8x7B".to_string(),
            description: "Mixture of Experts model from Mistral AI".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 15,
            category: Category::LLMModels,
            size: "~26GB".to_string(),
        },
        Package {
            id: "deepseek-coder-33b".to_string(),
            name: "DeepSeek Coder 33B".to_string(),
            description: "Specialized coding model".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 18,
            category: Category::LLMModels,
            size: "~19GB".to_string(),
        },
        Package {
            id: "yi-34b".to_string(),
            name: "Yi 34B".to_string(),
            description: "01.AI's bilingual model".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 16,
            category: Category::LLMModels,
            size: "~20GB".to_string(),
        },

        // LLM Models - Large (70B+)
        Package {
            id: "llama-3_3-70b".to_string(),
            name: "Llama 3.3 70B".to_string(),
            description: "Meta's flagship open model".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 35,
            category: Category::LLMModels,
            size: "~40GB".to_string(),
        },
        Package {
            id: "qwen-2_5-72b".to_string(),
            name: "Qwen 2.5 72B".to_string(),
            description: "Top-tier multilingual performance".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 38,
            category: Category::LLMModels,
            size: "~42GB".to_string(),
        },
        Package {
            id: "deepseek-v3".to_string(),
            name: "DeepSeek V3".to_string(),
            description: "671B MoE model, extremely capable".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 60,
            category: Category::LLMModels,
            size: "~90GB".to_string(),
        },

        // Video Generation
        Package {
            id: "mochi".to_string(),
            name: "Mochi-1".to_string(),
            description: "Open source video generation model, 10B params".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 20,
            category: Category::VideoGeneration,
            size: "~12GB".to_string(),
        },
        Package {
            id: "svd".to_string(),
            name: "Stable Video Diffusion".to_string(),
            description: "Stability AI's video diffusion model for ComfyUI".to_string(),
            dependencies: vec!["comfyui".to_string()],
            estimated_time: 15,
            category: Category::VideoGeneration,
            size: "~8GB".to_string(),
        },
        Package {
            id: "animatediff".to_string(),
            name: "AnimateDiff".to_string(),
            description: "Motion module for Stable Diffusion, animates images".to_string(),
            dependencies: vec!["comfyui".to_string()],
            estimated_time: 10,
            category: Category::VideoGeneration,
            size: "~4GB".to_string(),
        },
        Package {
            id: "cogvideo".to_string(),
            name: "CogVideoX-5B".to_string(),
            description: "Open source text-to-video model".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 25,
            category: Category::VideoGeneration,
            size: "~14GB".to_string(),
        },
        Package {
            id: "opensora".to_string(),
            name: "Open-Sora 2.0".to_string(),
            description: "High-quality video generation model".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 30,
            category: Category::VideoGeneration,
            size: "~16GB".to_string(),
        },
        Package {
            id: "ltxvideo".to_string(),
            name: "LTXVideo".to_string(),
            description: "Fast video generation with latent transformers".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 15,
            category: Category::VideoGeneration,
            size: "~7GB".to_string(),
        },

        // Image Generation
        Package {
            id: "flux-dev".to_string(),
            name: "Flux Dev".to_string(),
            description: "Black Forest Labs' powerful image generation model".to_string(),
            dependencies: vec!["comfyui".to_string()],
            estimated_time: 18,
            category: Category::ImageGeneration,
            size: "~12GB".to_string(),
        },
        Package {
            id: "flux-schnell".to_string(),
            name: "Flux Schnell".to_string(),
            description: "Fast version of Flux for quick iterations".to_string(),
            dependencies: vec!["comfyui".to_string()],
            estimated_time: 12,
            category: Category::ImageGeneration,
            size: "~12GB".to_string(),
        },
        Package {
            id: "sdxl".to_string(),
            name: "Stable Diffusion XL".to_string(),
            description: "High-resolution image generation".to_string(),
            dependencies: vec!["comfyui".to_string()],
            estimated_time: 10,
            category: Category::ImageGeneration,
            size: "~6.9GB".to_string(),
        },
        Package {
            id: "sd3-medium".to_string(),
            name: "SD3 Medium".to_string(),
            description: "Stability AI's Stable Diffusion 3 medium model".to_string(),
            dependencies: vec!["comfyui".to_string()],
            estimated_time: 12,
            category: Category::ImageGeneration,
            size: "~5.9GB".to_string(),
        },
        Package {
            id: "controlnet".to_string(),
            name: "ControlNet Models".to_string(),
            description: "Precise control over image generation".to_string(),
            dependencies: vec!["comfyui".to_string()],
            estimated_time: 8,
            category: Category::ImageGeneration,
            size: "~3.5GB".to_string(),
        },
        Package {
            id: "ipadapter".to_string(),
            name: "IP-Adapter".to_string(),
            description: "Image prompt adapter for style transfer".to_string(),
            dependencies: vec!["comfyui".to_string()],
            estimated_time: 5,
            category: Category::ImageGeneration,
            size: "~2.2GB".to_string(),
        },

        // Audio/Voice
        Package {
            id: "xtts-v2".to_string(),
            name: "XTTS v2".to_string(),
            description: "Coqui's multilingual text-to-speech with voice cloning".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 10,
            category: Category::AudioVoice,
            size: "~4GB".to_string(),
        },
        Package {
            id: "whisper-large-v3".to_string(),
            name: "Whisper Large v3".to_string(),
            description: "OpenAI's speech recognition model".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 8,
            category: Category::AudioVoice,
            size: "~3GB".to_string(),
        },
        Package {
            id: "musicgen".to_string(),
            name: "MusicGen".to_string(),
            description: "Meta's music generation model".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 12,
            category: Category::AudioVoice,
            size: "~5.5GB".to_string(),
        },
        Package {
            id: "audioldm2".to_string(),
            name: "AudioLDM 2".to_string(),
            description: "Text-to-audio and audio-to-audio generation".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 10,
            category: Category::AudioVoice,
            size: "~4.5GB".to_string(),
        },

        // Vision Models
        Package {
            id: "llava-v1_6-34b".to_string(),
            name: "LLaVA v1.6 34B".to_string(),
            description: "Large Language and Vision Assistant".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 22,
            category: Category::VisionModels,
            size: "~20GB".to_string(),
        },
        Package {
            id: "llava-llama3".to_string(),
            name: "LLaVA Llama3".to_string(),
            description: "Vision model based on Llama 3".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 12,
            category: Category::VisionModels,
            size: "~8GB".to_string(),
        },
        Package {
            id: "moondream".to_string(),
            name: "Moondream 2".to_string(),
            description: "Tiny vision language model (2B)".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 4,
            category: Category::VisionModels,
            size: "~1.7GB".to_string(),
        },
        Package {
            id: "bakllava".to_string(),
            name: "BakLLaVA".to_string(),
            description: "Mistral-based vision model".to_string(),
            dependencies: vec!["ollama".to_string()],
            estimated_time: 7,
            category: Category::VisionModels,
            size: "~4.7GB".to_string(),
        },

        // Tools
        Package {
            id: "vllm".to_string(),
            name: "vLLM".to_string(),
            description: "Fast LLM inference engine with PagedAttention".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 8,
            category: Category::Tools,
            size: "~2GB".to_string(),
        },
        Package {
            id: "sglang".to_string(),
            name: "SGLang".to_string(),
            description: "Structured generation language for LLMs".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 7,
            category: Category::Tools,
            size: "~1.5GB".to_string(),
        },
        Package {
            id: "aphrodite".to_string(),
            name: "Aphrodite Engine".to_string(),
            description: "PygmalionAI's inference engine".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 8,
            category: Category::Tools,
            size: "~1.8GB".to_string(),
        },
        Package {
            id: "llamafactory".to_string(),
            name: "LLaMA Factory".to_string(),
            description: "Easy LLM fine-tuning framework".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 10,
            category: Category::Tools,
            size: "~1GB".to_string(),
        },
        Package {
            id: "axolotl".to_string(),
            name: "Axolotl".to_string(),
            description: "Streamlined LLM fine-tuning".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 9,
            category: Category::Tools,
            size: "~900MB".to_string(),
        },
        Package {
            id: "deepspeed".to_string(),
            name: "DeepSpeed".to_string(),
            description: "Microsoft's distributed training optimization".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 12,
            category: Category::Tools,
            size: "~1.2GB".to_string(),
        },
        Package {
            id: "textgen-webui".to_string(),
            name: "Text Generation WebUI".to_string(),
            description: "Gradio web UI for running LLMs".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 10,
            category: Category::Tools,
            size: "~2GB".to_string(),
        },

        // Application
        Package {
            id: "anime".to_string(),
            name: "ANIME".to_string(),
            description: "Autonomous Natural Intelligence Management Engine - The AI orchestration CLI".to_string(),
            dependencies: vec![],
            estimated_time: 1,
            category: Category::Application,
            size: "~50MB".to_string(),
        },
        Package {
            id: "comfyui".to_string(),
            name: "ComfyUI".to_string(),
            description: "ComfyUI with manager and custom nodes".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 15,
            category: Category::Application,
            size: "~5GB".to_string(),
        },
        Package {
            id: "claude".to_string(),
            name: "Claude Code".to_string(),
            description: "Official Anthropic Claude CLI".to_string(),
            dependencies: vec!["core".to_string()],
            estimated_time: 2,
            category: Category::Application,
            size: "~100MB".to_string(),
        },
        Package {
            id: "stable-diffusion-webui".to_string(),
            name: "SD WebUI (AUTOMATIC1111)".to_string(),
            description: "Popular web UI for Stable Diffusion".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 12,
            category: Category::Application,
            size: "~4GB".to_string(),
        },
        Package {
            id: "fooocus".to_string(),
            name: "Fooocus".to_string(),
            description: "Simplified Stable Diffusion interface".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 10,
            category: Category::Application,
            size: "~3.5GB".to_string(),
        },
        Package {
            id: "invokeai".to_string(),
            name: "InvokeAI".to_string(),
            description: "Professional creative AI application".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string(), "pytorch".to_string()],
            estimated_time: 14,
            category: Category::Application,
            size: "~5GB".to_string(),
        },
        Package {
            id: "open-webui".to_string(),
            name: "Open WebUI".to_string(),
            description: "Self-hosted ChatGPT-like interface for Ollama".to_string(),
            dependencies: vec!["core".to_string(), "ollama".to_string()],
            estimated_time: 5,
            category: Category::Application,
            size: "~500MB".to_string(),
        },
        Package {
            id: "jupyter".to_string(),
            name: "Jupyter Lab".to_string(),
            description: "Interactive notebook environment".to_string(),
            dependencies: vec!["core".to_string(), "python".to_string()],
            estimated_time: 4,
            category: Category::Application,
            size: "~800MB".to_string(),
        },
        Package {
            id: "code-server".to_string(),
            name: "VS Code Server".to_string(),
            description: "VS Code in the browser".to_string(),
            dependencies: vec!["core".to_string()],
            estimated_time: 6,
            category: Category::Application,
            size: "~300MB".to_string(),
        },
    ]
}
