package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/joshkornreich/anime/internal/config"
	"github.com/joshkornreich/anime/internal/ssh"
	"github.com/joshkornreich/anime/internal/theme"
	"github.com/spf13/cobra"
)

var aliasOllamaCmd = &cobra.Command{
	Use:   "alias-ollama",
	Short: "Create shell aliases for Ollama models",
	Long:  "Automatically create shell aliases for all installed Ollama models, so you can run 'mixtral' instead of 'ollama run mixtral:8x7b'",
	RunE:  runAliasOllama,
}

func init() {
	rootCmd.AddCommand(aliasOllamaCmd)
}

func runAliasOllama(cmd *cobra.Command, args []string) error {
	fmt.Println()
	fmt.Println(theme.RenderBanner("🤖 OLLAMA MODEL ALIASES"))
	fmt.Println()

	// Get list of ollama models
	var models []string
	var err error

	// Try local first
	models, err = getLocalOllamaModels()
	if err != nil || len(models) == 0 {
		// Try remote
		models, err = getRemoteOllamaModels()
	}

	if err != nil {
		return fmt.Errorf("failed to get ollama models: %w", err)
	}

	if len(models) == 0 {
		fmt.Println(theme.WarningStyle.Render("⚠️  No Ollama models found"))
		fmt.Println()
		fmt.Println(theme.InfoStyle.Render("💡 Install some models first:"))
		fmt.Printf("  %s\n", theme.HighlightStyle.Render("ollama pull mixtral:8x7b"))
		fmt.Printf("  %s\n", theme.HighlightStyle.Render("ollama pull llama3.3:70b"))
		fmt.Println()
		return nil
	}

	fmt.Printf("  Found %s Ollama models\n", theme.HighlightStyle.Render(fmt.Sprintf("%d", len(models))))
	fmt.Println()

	// Create aliases
	aliases := make(map[string]string)
	for _, model := range models {
		alias := generateAlias(model)
		aliases[alias] = model
	}

	// Display aliases
	fmt.Println(theme.SuccessStyle.Render("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"))
	fmt.Println(theme.InfoStyle.Render("📝 Generated Aliases"))
	fmt.Println(theme.SuccessStyle.Render("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"))
	fmt.Println()

	for alias, model := range aliases {
		fmt.Printf("  %s → %s\n",
			theme.HighlightStyle.Render(alias),
			theme.DimTextStyle.Render("ollama run "+model))
	}
	fmt.Println()

	// Generate shell script
	shellScript := generateAliasScript(aliases)

	// Determine shell config file
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	shellConfigFile := filepath.Join(home, ".bashrc")
	if shell := os.Getenv("SHELL"); strings.Contains(shell, "zsh") {
		shellConfigFile = filepath.Join(home, ".zshrc")
	}

	// Check if file exists
	_, err = os.Stat(shellConfigFile)
	fileExists := err == nil

	fmt.Println(theme.SuccessStyle.Render("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"))
	fmt.Println(theme.InfoStyle.Render("💾 Installation"))
	fmt.Println(theme.SuccessStyle.Render("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"))
	fmt.Println()

	if fileExists {
		// Append to existing file
		fmt.Printf("  Adding aliases to: %s\n", theme.InfoStyle.Render(shellConfigFile))
		fmt.Println()

		// Check if aliases already exist
		content, err := os.ReadFile(shellConfigFile)
		if err != nil {
			return err
		}

		if strings.Contains(string(content), "# Ollama Model Aliases") {
			// Remove old aliases section
			lines := strings.Split(string(content), "\n")
			var newLines []string
			skip := false
			for _, line := range lines {
				if strings.Contains(line, "# Ollama Model Aliases - Generated by anime") {
					skip = true
				}
				if skip && (strings.TrimSpace(line) == "" || strings.HasPrefix(line, "# End Ollama Aliases")) {
					skip = false
					continue
				}
				if !skip {
					newLines = append(newLines, line)
				}
			}
			content = []byte(strings.Join(newLines, "\n"))
		}

		// Append new aliases
		f, err := os.OpenFile(shellConfigFile, os.O_APPEND|os.O_WRONLY, 0644)
		if err != nil {
			return err
		}
		defer f.Close()

		if _, err := f.WriteString("\n" + shellScript); err != nil {
			return err
		}

		fmt.Println(theme.SuccessStyle.Render("✓ Aliases installed!"))
		fmt.Println()
		fmt.Println(theme.InfoStyle.Render("🔄 To activate the aliases, run:"))
		fmt.Printf("  %s\n", theme.HighlightStyle.Render("source "+shellConfigFile))
		fmt.Println()
		fmt.Println(theme.DimTextStyle.Render("  Or restart your terminal"))
		fmt.Println()
	} else {
		// File doesn't exist, show manual instructions
		fmt.Println(theme.WarningStyle.Render("⚠️  Shell config file not found"))
		fmt.Println()
		fmt.Println(theme.InfoStyle.Render("💡 Add these aliases to your shell config:"))
		fmt.Println()
		fmt.Println(theme.DimTextStyle.Render(shellScript))
		fmt.Println()
	}

	return nil
}

func getLocalOllamaModels() ([]string, error) {
	output, err := runLocalCommand("ollama list 2>/dev/null | tail -n +2 | awk '{print $1}'")
	if err != nil {
		return nil, err
	}

	lines := strings.Split(strings.TrimSpace(output), "\n")
	var models []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" {
			models = append(models, line)
		}
	}

	return models, nil
}

func getRemoteOllamaModels() ([]string, error) {
	cfg, err := config.Load()
	if err != nil {
		return nil, err
	}

	// Get lambda server
	lambdaTarget := cfg.GetAlias("lambda")
	if lambdaTarget == "" {
		if server, err := cfg.GetServer("lambda"); err == nil {
			lambdaTarget = fmt.Sprintf("%s@%s", server.User, server.Host)
		}
	}

	if lambdaTarget == "" {
		return nil, fmt.Errorf("lambda server not configured")
	}

	// Parse target
	var user, host string
	if strings.Contains(lambdaTarget, "@") {
		parts := strings.SplitN(lambdaTarget, "@", 2)
		user = parts[0]
		host = parts[1]
	} else {
		user = "ubuntu"
		host = lambdaTarget
	}

	// Connect
	client, err := ssh.NewClient(host, user, "")
	if err != nil {
		return nil, err
	}
	defer client.Close()

	// Get models
	output, err := client.RunCommand("ollama list 2>/dev/null | tail -n +2 | awk '{print $1}'")
	if err != nil {
		return nil, err
	}

	lines := strings.Split(strings.TrimSpace(output), "\n")
	var models []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" {
			models = append(models, line)
		}
	}

	return models, nil
}

func generateAlias(model string) string {
	// Remove version tags and create simple alias
	// mixtral:8x7b -> mixtral
	// llama3.3:70b -> llama3
	// qwen3:14b -> qwen3 or qwen14b

	parts := strings.Split(model, ":")
	base := parts[0]

	// Handle special cases
	switch {
	case strings.HasPrefix(base, "llama"):
		// llama3.3 -> llama3
		return strings.Split(base, ".")[0]
	case strings.HasPrefix(base, "qwen"):
		// qwen3:14b -> qwen14b
		if len(parts) > 1 {
			return strings.Replace(base, ".", "", -1) + parts[1]
		}
		return strings.Replace(base, ".", "", -1)
	case strings.HasPrefix(base, "deepseek"):
		// deepseek-coder:33b -> deepseek
		return "deepseek"
	default:
		return base
	}
}

func generateAliasScript(aliases map[string]string) string {
	var script strings.Builder

	script.WriteString("# Ollama Model Aliases - Generated by anime\n")
	script.WriteString("# Run 'anime alias-ollama' to regenerate\n\n")

	for alias, model := range aliases {
		script.WriteString(fmt.Sprintf("alias %s='ollama run %s'\n", alias, model))
	}

	script.WriteString("\n# End Ollama Aliases\n")

	return script.String()
}
