package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/joshkornreich/anime/internal/launch"
	"github.com/joshkornreich/anime/internal/theme"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var initCmd = &cobra.Command{
	Use:   "init [path]",
	Short: "Generate anime.yaml from detected project structure",
	Long: `Scans the directory for services and generates an anime.yaml configuration file.

This command detects:
  - Project type (Node.js, Python, Go, Rust)
  - Framework (Next.js, FastAPI, Django, Express, etc.)
  - Run commands and ports
  - Database usage (Postgres, MySQL, MongoDB, Redis)
  - Multi-service stacks (monorepo detection)

The generated anime.yaml can be edited and used with 'anime stack deploy'.

Examples:
  anime init                    # Initialize in current directory
  anime init ./myproject        # Initialize in specific directory
  anime init ~/projects/app     # Initialize with absolute path`,
	Args: cobra.MaximumNArgs(1),
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

// detectedService holds information about a detected service
type detectedService struct {
	name    string
	path    string
	project *launch.DetectedProject
	dbInfo  *launch.DatabaseInfo
}

// stackConfig mirrors the YAML structure for anime.yaml
type stackConfig struct {
	Name     string                   `yaml:"name"`
	Services map[string]serviceConfig `yaml:"services"`
	Routing  *routingConfig           `yaml:"routing,omitempty"`
	SSL      bool                     `yaml:"ssl,omitempty"`
}

type serviceConfig struct {
	Path      string            `yaml:"path,omitempty"`
	Port      int               `yaml:"port,omitempty"`
	Domain    string            `yaml:"domain,omitempty"`
	Build     string            `yaml:"build,omitempty"`
	Start     string            `yaml:"start,omitempty"`
	Env       map[string]string `yaml:"env,omitempty"`
	DependsOn []string          `yaml:"depends_on,omitempty"`
	Type      string            `yaml:"type,omitempty"`
	Name      string            `yaml:"name,omitempty"`
}

type routingConfig struct {
	Domain string            `yaml:"domain,omitempty"`
	Paths  map[string]string `yaml:"paths,omitempty"`
}

func runInit(cmd *cobra.Command, args []string) error {
	// Get path (default to current dir)
	path := "."
	if len(args) > 0 {
		path = args[0]
	}

	// Resolve to absolute path
	absPath, err := filepath.Abs(path)
	if err != nil {
		return fmt.Errorf("failed to resolve path: %w", err)
	}

	// Check if path exists
	info, err := os.Stat(absPath)
	if err != nil {
		return fmt.Errorf("path does not exist: %s", absPath)
	}
	if !info.IsDir() {
		return fmt.Errorf("path is not a directory: %s", absPath)
	}

	fmt.Println()
	fmt.Println(theme.TitleStyle.Render("ANIME INIT"))
	fmt.Println()
	fmt.Printf("  %s %s\n", theme.DimTextStyle.Render("Scanning:"), theme.InfoStyle.Render(absPath))
	fmt.Println()

	// Detect project structure
	services := detectServices(absPath)

	if len(services) == 0 {
		fmt.Println(theme.WarningStyle.Render("  No services detected"))
		fmt.Println()
		fmt.Println(theme.DimTextStyle.Render("  Looked for: package.json, go.mod, requirements.txt, pyproject.toml, Cargo.toml"))
		fmt.Println()
		return nil
	}

	// Print detected services
	fmt.Println(theme.HeaderStyle.Render("Detected Services:"))
	fmt.Println()

	for _, svc := range services {
		printServiceInfo(svc)
	}

	// Generate anime.yaml config
	config := generateConfig(absPath, services)

	// Check if anime.yaml already exists
	yamlPath := filepath.Join(absPath, "anime.yaml")
	if fileExistsCheck(yamlPath) {
		fmt.Println(theme.WarningStyle.Render("  anime.yaml already exists"))
		fmt.Println()
		fmt.Print(theme.DimTextStyle.Render("  Overwrite? (y/N): "))

		reader := bufio.NewReader(os.Stdin)
		response, _ := reader.ReadString('\n')
		response = strings.TrimSpace(strings.ToLower(response))

		if response != "y" && response != "yes" {
			fmt.Println()
			fmt.Println(theme.DimTextStyle.Render("  Cancelled"))
			fmt.Println()
			return nil
		}
		fmt.Println()
	}

	// Write anime.yaml
	data, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("failed to generate YAML: %w", err)
	}

	// Add header comment
	header := "# Generated by anime init\n# Edit this file to customize your deployment\n\n"
	if err := os.WriteFile(yamlPath, []byte(header+string(data)), 0644); err != nil {
		return fmt.Errorf("failed to write anime.yaml: %w", err)
	}

	// Print summary
	fmt.Println(theme.SuccessStyle.Render("  Created anime.yaml"))
	fmt.Println()
	fmt.Printf("  %s %s\n", theme.DimTextStyle.Render("File:"), theme.InfoStyle.Render(yamlPath))
	fmt.Println()

	// Print next steps
	fmt.Println(theme.HeaderStyle.Render("Next Steps:"))
	fmt.Println()
	fmt.Printf("  1. %s\n", theme.DimTextStyle.Render("Review and edit anime.yaml as needed"))
	fmt.Printf("  2. %s\n", theme.DimTextStyle.Render("Set environment variables in the env: sections"))
	fmt.Printf("  3. %s\n", theme.HighlightStyle.Render("anime stack deploy"))
	fmt.Println()

	return nil
}

// detectServices scans the path for services
func detectServices(basePath string) []detectedService {
	var services []detectedService

	// Known service subdirectory names
	knownServiceDirs := []string{
		"ui", "frontend", "web", "client", "app",
		"server", "api", "backend", "service",
		"admin", "dashboard", "portal",
		"worker", "jobs", "queue",
	}

	// First check if the base path itself is a single service
	rootProject := launch.AnalyzeProject(basePath)
	if rootProject.Project != nil && rootProject.Project.Type != launch.ProjectUnknown {
		// Check if this is a monorepo or single service
		hasSubServices := false
		for _, dir := range knownServiceDirs {
			subPath := filepath.Join(basePath, dir)
			if fileExistsCheck(subPath) {
				if hasProjectFiles(subPath) {
					hasSubServices = true
					break
				}
			}
		}

		if !hasSubServices {
			// Single service project
			services = append(services, detectedService{
				name:    filepath.Base(basePath),
				path:    ".",
				project: rootProject.Project,
				dbInfo:  rootProject.Database,
			})
			return services
		}
	}

	// Multi-service detection: scan known directories
	for _, dir := range knownServiceDirs {
		subPath := filepath.Join(basePath, dir)
		if !fileExistsCheck(subPath) {
			continue
		}

		result := launch.AnalyzeProject(subPath)
		if result.Project != nil && result.Project.Type != launch.ProjectUnknown {
			services = append(services, detectedService{
				name:    dir,
				path:    dir,
				project: result.Project,
				dbInfo:  result.Database,
			})
		}
	}

	// Also scan for other directories with project files
	entries, err := os.ReadDir(basePath)
	if err != nil {
		return services
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		name := entry.Name()

		// Skip hidden directories and known non-service dirs
		if strings.HasPrefix(name, ".") ||
			name == "node_modules" ||
			name == "vendor" ||
			name == "dist" ||
			name == "build" ||
			name == "__pycache__" ||
			name == "venv" ||
			name == ".venv" ||
			name == "target" {
			continue
		}

		// Skip if already detected
		alreadyDetected := false
		for _, svc := range services {
			if svc.name == name {
				alreadyDetected = true
				break
			}
		}
		if alreadyDetected {
			continue
		}

		subPath := filepath.Join(basePath, name)
		result := launch.AnalyzeProject(subPath)
		if result.Project != nil && result.Project.Type != launch.ProjectUnknown {
			services = append(services, detectedService{
				name:    name,
				path:    name,
				project: result.Project,
				dbInfo:  result.Database,
			})
		}
	}

	return services
}

// hasProjectFiles checks if a directory contains project files
func hasProjectFiles(path string) bool {
	projectFiles := []string{
		"package.json",
		"go.mod",
		"requirements.txt",
		"pyproject.toml",
		"Cargo.toml",
		"Makefile",
	}

	for _, file := range projectFiles {
		if fileExistsCheck(filepath.Join(path, file)) {
			return true
		}
	}
	return false
}

// printServiceInfo displays detected service information
func printServiceInfo(svc detectedService) {
	fmt.Printf("  %s %s\n", theme.HighlightStyle.Render(svc.name), theme.DimTextStyle.Render("("+svc.path+")"))

	typeStr := string(svc.project.Type)
	if svc.project.Framework != "" && svc.project.Framework != typeStr {
		typeStr = svc.project.Framework
	}
	fmt.Printf("    %s %s\n", theme.DimTextStyle.Render("Type:"), theme.InfoStyle.Render(typeStr))
	fmt.Printf("    %s %d\n", theme.DimTextStyle.Render("Port:"), svc.project.Port)
	fmt.Printf("    %s %s\n", theme.DimTextStyle.Render("Start:"), theme.DimTextStyle.Render(svc.project.RunCommand))

	if svc.dbInfo != nil && svc.dbInfo.Detected {
		dbType := string(svc.dbInfo.PrimaryType)
		if dbType == "" || dbType == "unknown" {
			dbType = "detected"
		}
		fmt.Printf("    %s %s\n", theme.DimTextStyle.Render("Database:"), theme.WarningStyle.Render(dbType))
	}

	fmt.Println()
}

// generateConfig creates the anime.yaml configuration
func generateConfig(basePath string, services []detectedService) *stackConfig {
	appName := filepath.Base(basePath)
	// Clean up app name (remove special characters)
	appName = strings.ToLower(appName)
	appName = strings.ReplaceAll(appName, " ", "-")
	appName = strings.ReplaceAll(appName, "_", "-")

	config := &stackConfig{
		Name:     appName,
		Services: make(map[string]serviceConfig),
		SSL:      true,
	}

	// Track if we need database service
	needsDatabase := false
	var primaryDbType launch.DatabaseType

	// Generate service configs
	for _, svc := range services {
		sc := serviceConfig{
			Port:  svc.project.Port,
			Start: svc.project.RunCommand,
		}

		// Only set path if not root
		if svc.path != "." {
			sc.Path = svc.path
		}

		// Set build command for compiled languages or build-required frameworks
		buildCmd := getBuildCommand(svc.project)
		if buildCmd != "" {
			sc.Build = buildCmd
		}

		// Generate domain based on service role
		sc.Domain = generateDomain(appName, svc.name)

		// Add placeholder environment variables
		sc.Env = generateEnvPlaceholders(svc)

		// Check database needs
		if svc.dbInfo != nil && svc.dbInfo.NeedsDatabase {
			needsDatabase = true
			if svc.dbInfo.PrimaryType != "" && svc.dbInfo.PrimaryType != launch.DBUnknown {
				primaryDbType = svc.dbInfo.PrimaryType
			}
			sc.DependsOn = []string{"db"}
		}

		config.Services[svc.name] = sc
	}

	// Add database service if needed
	if needsDatabase {
		dbConfig := serviceConfig{
			Type: "postgres",
			Name: appName + "_db",
		}
		if primaryDbType == launch.DBMySQL {
			dbConfig.Type = "mysql"
		} else if primaryDbType == launch.DBMongo {
			dbConfig.Type = "mongo"
		}
		config.Services["db"] = dbConfig
	}

	// Add routing config if multi-service
	if len(services) > 1 {
		config.Routing = generateRouting(appName, services)
	}

	return config
}

// getBuildCommand returns appropriate build command for the project type
func getBuildCommand(project *launch.DetectedProject) string {
	switch project.Type {
	case launch.ProjectNodeJS:
		switch project.Framework {
		case "next", "nuxt", "vite", "create-react-app":
			pm := project.PackageManager
			if pm == "" {
				pm = "npm"
			}
			return pm + " run build"
		}
	case launch.ProjectGo:
		return "go build -o app ."
	case launch.ProjectRust:
		return "cargo build --release"
	case launch.ProjectPython:
		// Python typically doesn't need build, but check for pip install
		return ""
	}
	return ""
}

// generateDomain creates a domain name for a service
func generateDomain(appName, serviceName string) string {
	baseDomain := appName + ".example.com"

	// Map common service names to subdomains
	switch serviceName {
	case "ui", "frontend", "web", "client", "app":
		return baseDomain
	case "server", "api", "backend", "service":
		return "api." + baseDomain
	case "admin", "dashboard":
		return "admin." + baseDomain
	case "worker", "jobs", "queue":
		return "" // Workers typically don't need domains
	default:
		// For single service or unknown names
		if serviceName == appName {
			return baseDomain
		}
		return serviceName + "." + baseDomain
	}
}

// generateEnvPlaceholders creates placeholder environment variables
func generateEnvPlaceholders(svc detectedService) map[string]string {
	env := make(map[string]string)

	// Add PORT
	env["PORT"] = fmt.Sprintf("%d", svc.project.Port)

	// Add NODE_ENV for Node.js
	if svc.project.Type == launch.ProjectNodeJS {
		env["NODE_ENV"] = "production"
	}

	// Add database URL if database detected
	if svc.dbInfo != nil && svc.dbInfo.NeedsDatabase {
		env["DATABASE_URL"] = "${DB_URL}"
	}

	return env
}

// generateRouting creates routing configuration for multi-service stacks
func generateRouting(appName string, services []detectedService) *routingConfig {
	routing := &routingConfig{
		Domain: appName + ".example.com",
		Paths:  make(map[string]string),
	}

	for _, svc := range services {
		switch svc.name {
		case "api", "server", "backend", "service":
			routing.Paths["/api"] = svc.name
		case "ui", "frontend", "web", "client", "app":
			routing.Paths["/"] = svc.name
		case "admin", "dashboard":
			routing.Paths["/admin"] = svc.name
		}
	}

	// Only return routing if we have path mappings
	if len(routing.Paths) == 0 {
		return nil
	}

	return routing
}

// fileExistsCheck checks if a file or directory exists
func fileExistsCheck(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
